### ISSUE TITLE
Outdated plugin publishing metadata

### ISSUE THREAD

**Issue by cobexer** [GlebSolovev/bitcode-tools#5]
Outdated plugin publishing metadata

https://github.com/JetBrains-Research/bitcode-tools/blob/ca6cdd09f93ae64f160f74069078613b5f6a1470/plugin-build/gradle.properties#L6

https://github.com/JetBrains-Research/bitcode-tools/blob/ca6cdd09f93ae64f160f74069078613b5f6a1470/plugin-build/gradle.properties#L7

**Comment by GlebSolovev** [comment]
Hi, @cobexer!
 
Thank you for noticing the outdated info. I’ve already fixed it and published a newer version.
Thanks in advance for reviewing it too.
 
--
Sincerely,
Gleb Solovev

**Comment by cobexer** [comment]
Done :)
